name: Build Thetis

on:
  # Push to master or PR
  push:
    branches:
      - master
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Scheduled build at 0230 UTC on Monday mornings to detect bitrot.
    - cron:  '30 2 * * 1'

jobs:
  build:
    name: "Build Thetis"
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux]
    # The docker container to use.
    container:
      image: firedrakeproject/firedrake-vanilla-default:latest
    env:
      # Make sure that tests with >2 processes are not silently skipped
      PYTEST_MPI_MAX_NPROCS: 2
    steps:
      - name: Fix HOME
        # For unknown reasons GitHub actions overwrite HOME to /github/home
        # which will break everything unless fixed
        # (https://github.com/actions/runner/issues/863)
        run: echo "HOME=/root" >> "$GITHUB_ENV"

      - name: Pre-cleanup
        run: |
          : # Wipe everything away in the current directory
          find . -delete
          firedrake-clean

      - uses: actions/checkout@v4
        with:
          # Download Thetis into a subdirectory not called 'thetis' to make sure
          # that the package installs correctly. Otherwise 'import thetis' may
          # work even if the installation failed because it is a subdirectory.
          path: thetis-repo

      - name: Install Thetis
        id: install
        run: |
          : # Pass '--system-site-packages' so Firedrake can be found
          python3 -m venv --system-site-packages venv-thetis
          . venv-thetis/bin/activate
          pip install ./thetis-repo[dev]
          pip list

      - name: Lint
        run: |
          . venv-thetis/bin/activate
          pip install flake8
          make -C thetis-repo lint

      - name: Test Thetis
        # Run even if the step above failed
        if: success() || steps.install.conclusion == 'success'
        run: |
          . venv-thetis/bin/activate
          : # Run the serial tests (coverage measurement saved in .coverage file)
          python -m pytest --cov=thetis --cov-report=term-missing --cov-append -n 12 --verbose --durations=0 --durations-min=60.0 \
          -m "parallel[1] or not parallel" thetis-repo/test
          : # Run the parallel tests (note that xdist is not valid in parallel)
          mpiexec -n 2 python -m pytest --cov=thetis --cov-report=term-missing --cov-append --verbose --durations=0 --durations-min=60.0 \
          -m parallel[2] thetis-repo/test

      - name: Test Thetis adjoint
        if: success() || steps.install.conclusion == 'success'
        run: |
          firedrake-clean
          . venv-thetis/bin/activate
          python -m pytest --cov=thetis --cov-report=term-missing --cov-append -n 12 --verbose --durations=0 thetis-repo/test_adjoint

      - name: Upload coverage to Codecov (dry run)
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          dry-run: true  # fail_ci_if_error: true

      - name: Post-cleanup
        if: always()
        run: |
          find . -delete
          firedrake-clean
