name: Core Build & Test

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to test (e.g. master or release)'
        required: true
        type: string
      image:
        description: 'Docker image to use for Firedrake'
        required: true
        type: string

jobs:
  build:
    name: "Build & Test (${{ inputs.branch }})"
    # The type of runner that the job will run on
    runs-on: [self-hosted, Linux]
    # The docker container to use.
    container:
      image: ${{ inputs.image }}
    env:
      # Make sure that tests with >2 processes are not silently skipped
      PYTEST_MPI_MAX_NPROCS: 2
      FIREDRAKE_IMAGE_MAIN: firedrakeproject/firedrake-vanilla-default:dev-main
      FIREDRAKE_IMAGE_RELEASE: firedrakeproject/firedrake-vanilla-default:latest
    steps:
      - name: Fix HOME
        # For unknown reasons GitHub actions overwrite HOME to /github/home
        # which will break everything unless fixed
        # (https://github.com/actions/runner/issues/863)
        run: echo "HOME=/root" >> "$GITHUB_ENV"

      - name: Info
        run: |
          echo "===================================="
          echo "Running Thetis CI"
          echo "Branch: ${{ inputs.branch }}"
          echo "Firedrake Docker image: ${{ inputs.image }}"
          echo "===================================="

      - name: Pre-cleanup
        run: |
          : # Wipe everything away in the current directory
          find . -delete || true
          firedrake-clean || true

      - name: Checkout Thetis
        uses: actions/checkout@v5
        with:
          # Download Thetis into a subdirectory not called 'thetis' to make sure
          # that the package installs correctly. Otherwise 'import thetis' may
          # work even if the installation failed because it is a subdirectory.
          ref: ${{ inputs.branch }}
          path: thetis-repo

      - name: Install Thetis
        id: install
        run: |
          : # Pass '--system-site-packages' so Firedrake can be found
          python3 -m venv --system-site-packages venv-thetis
          . venv-thetis/bin/activate
          pip install ./thetis-repo
          pip list

      - name: Lint
        run: |
          . venv-thetis/bin/activate
          pip install flake8
          make -C thetis-repo lint

      - name: Test Thetis (serial)
        # Run even if the step above failed
        if: success() || steps.install.conclusion == 'success'
        run: |
          . venv-thetis/bin/activate
          : # Run the serial tests
          python -m pytest -n 12 --verbose --durations=0 --durations-min=60.0 \
            -m "parallel[1] or not parallel" thetis-repo/test

      - name: Test Thetis (parallel)
        if: success() || steps.install.conclusion == 'success'
        run: |
          . venv-thetis/bin/activate
          : # Run the parallel tests (note that xdist is not valid in parallel)
          mpiexec -n 2 python -m pytest --verbose --durations=0 --durations-min=60.0 \
            -m parallel[2] thetis-repo/test

      - name: Test Thetis adjoint
        if: success() || steps.install.conclusion == 'success'
        run: |
          firedrake-clean
          . venv-thetis/bin/activate
          python -m pytest -n 8 --verbose --durations=0 thetis-repo/test_adjoint

      - name: Post-cleanup
        if: always()
        run: |
          find . -delete || true
          firedrake-clean || true
